# Generated by Django 3.0.5 on 2020-04-26 14:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 14, 32, 38, 201003, tzinfo=utc)),
        ),
    ]
