# Generated by Django 3.0.5 on 2020-04-26 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 14, 33, 54, 274594, tzinfo=utc)),
        ),
    ]
