# Generated by Django 3.0.5 on 2020-04-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200426_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='film_style',
            field=models.CharField(default='truzas', max_length=255),
        ),
    ]
